const state={lang:'de'};
const detailCopy={
 domain:{de:'Domänenwissen entscheidet, ob AI nur generisch wirkt oder tatsächlich den Kern professioneller Arbeit verbessert.',en:'Domain expertise determines whether AI stays generic or genuinely improves the core of professional work.'},
 institution:{de:'Institutionelle Logiken erklären, warum gute Ideen scheitern, Entscheidungen langsam werden oder Veränderung an Regeln, Anreizen und Zuständigkeiten hängen bleibt.',en:'Institutional logic explains why good ideas fail, decisions slow down, and change gets stuck in rules, incentives and responsibilities.'},
 technology:{de:'Technologie verändert Reichweite, Geschwindigkeit und Möglichkeiten — und erzeugt gleichzeitig neue Abhängigkeiten, Risiken und Machtpositionen.',en:'Technology changes reach, speed and possibility — while also creating new dependencies, risks and positions of power.'},
 power:{de:'Urteilskraft und Macht entscheiden, welche Ziele verfolgt werden, welches Wissen zählt und wer über neue technologische Möglichkeiten verfügen kann.',en:'Judgement and power determine which goals are pursued, whose knowledge counts and who can act on new technological possibilities.'}
};
function setLang(lang){state.lang=lang;localStorage.setItem('furatLang',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-lang]').forEach(el=>el.style.display=el.dataset.lang===lang?'':'none');document.querySelectorAll('[data-setlang]').forEach(b=>b.classList.toggle('active',b.dataset.setlang===lang));const lf=document.getElementById('langField');if(lf)lf.value=lang;document.querySelectorAll('select option[data-de]').forEach(o=>o.textContent=o.dataset[lang]);updateDetail();updateLightboxCaption();}
document.querySelectorAll('[data-setlang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.setlang)));
let activeNode='domain';function updateDetail(){const d=document.getElementById('nodeDetail');if(d)d.textContent=detailCopy[activeNode][state.lang]}
document.querySelectorAll('.node').forEach(n=>n.addEventListener('click',()=>{document.querySelectorAll('.node').forEach(x=>x.classList.remove('active'));n.classList.add('active');activeNode=n.dataset.node;updateDetail()}));
const chips=[...document.querySelectorAll('.chip')];chips.forEach(c=>c.addEventListener('click',()=>{chips.forEach(x=>x.classList.remove('active'));c.classList.add('active');const i=document.getElementById('interest');if(i)i.value=c.dataset.value}));
window.addEventListener('pointermove',e=>{const o=document.getElementById('orb');if(!o)return;const x=(e.clientX/window.innerWidth-.5)*36,y=(e.clientY/window.innerHeight-.5)*28;o.style.setProperty('--mx',x+'px');o.style.setProperty('--my',y+'px')});
const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycby3nJhHH_fwWoQ6ffLlikKUw2TxsJRw4AW8JzOS-xAWNcF6v_rhAuQ1YDjJE4eZwkM/exec';
const form=document.getElementById('leadForm');if(form)form.addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('status');const time=document.getElementById('submittedAt');if(time)time.value=new Date().toISOString();const interest=document.getElementById('interest');if(interest&&!interest.value){status.textContent=state.lang==='de'?'Bitte wähle kurz aus, worum es geht.':'Please choose what your inquiry is about.';return}const fd=new FormData(e.currentTarget);if(fd.get('website'))return;const payload=Object.fromEntries(fd.entries());status.textContent=state.lang==='de'?'Wird gesendet …':'Sending …';if(APPS_SCRIPT_URL.includes('PASTE_YOUR')){console.log('Lead payload',payload);status.textContent=state.lang==='de'?'Demo-Modus: Formular ist vorbereitet. Apps-Script-URL noch einsetzen.':'Demo mode: form is ready. Add the Apps Script URL to activate storage.';return}try{await fetch(APPS_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});status.textContent=state.lang==='de'?'Danke — deine Anfrage wurde gesendet.':'Thank you — your inquiry has been sent.';e.currentTarget.reset();chips.forEach(x=>x.classList.remove('active'));if(interest)interest.value='';}catch(err){status.textContent=state.lang==='de'?'Senden hat nicht funktioniert. Bitte versuche es erneut.':'Something went wrong. Please try again.';}});
const lightbox=document.getElementById('lightbox');const lightboxImg=document.getElementById('lightboxImg');const lightboxCap=document.getElementById('lightboxCap');let currentCap={de:'',en:''};function updateLightboxCaption(){if(lightboxCap)lightboxCap.textContent=currentCap[state.lang]||''}
document.querySelectorAll('[data-img]').forEach(card=>card.addEventListener('click',()=>{if(!lightbox)return;currentCap={de:card.dataset.capDe||'',en:card.dataset.capEn||''};lightboxImg.src=card.dataset.img;updateLightboxCaption();lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false')}));function closeLightbox(){if(!lightbox)return;lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');lightboxImg.src=''}const close=document.getElementById('closeLightbox');if(close)close.addEventListener('click',closeLightbox);if(lightbox)lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox()});
setLang(localStorage.getItem('furatLang')||'de');updateDetail();
